import {
    createDefaultModule, createDefaultSharedModule, DefaultSharedModuleContext, inject,
    LangiumServices, LangiumSharedServices, Module, PartialLangiumServices
} from 'langium';
import { BifrostGeneratedModule, BifrostGeneratedSharedModule } from './generated/module';
import { BifrostValidationRegistry } from './bifrost-validator';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type BifrostAddedServices = {
    validation: {
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type BifrostServices = LangiumServices & BifrostAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const BifrostModule: Module<BifrostServices, PartialLangiumServices & BifrostAddedServices> = {
    validation: {
        ValidationRegistry: (services) => new BifrostValidationRegistry(services),
    },
    references: {
        ScopeProvider: (services) => new BifrostScopeProvider(services)
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createBifrostServices(context?: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    Bifrost: BifrostServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        BifrostGeneratedSharedModule
    );
    const Bifrost = inject(
        createDefaultModule({ shared }),
        BifrostGeneratedModule,
        BifrostModule
    );
    shared.ServiceRegistry.register(Bifrost);
    return { shared, Bifrost };
}
